deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml

apisix:
  node_listen: 9080
  enable_admin: true

plugins:
  - openid-connect
  - grpc-transcode

nginx_config:
  http_configuration_snippet: |
    # Caché necesaria para el plugin authz-openfga
    lua_shared_dict authz_openfga_authorization_model 1m;
  error_log_level: "debug"